---
name: 💬 Question / Discussion
about: Ask a question or start a discussion
title: '[Q] '
labels: ['question']
assignees: []
body:
  - type: textarea
    id: question
    attributes:
      label: Your question
      placeholder: How do I...?
    validations:
      required: true
---
