"""Built-in report & vulnerability template strings plus a tiny render engine.

This module is intentionally dependency-free: every template is a plain
multi-line ``str`` that uses ``{placeholder}`` substitution.  The
:func:`render_template` helper substitutes every recognised placeholder
with the matching context value **or** an empty string (so a partial
context never raises ``KeyError`` and never leaves a literal ``{...}``
behind in the rendered output).

Public surface
--------------

Templates (module-level ``str`` constants):
    * ``DEFAULT_TEMPLATE``              — standard pentest report skeleton
    * ``EXECUTIVE_SUMMARY_TEMPLATE``    — short executive summary
    * ``DETAILED_FINDINGS_TEMPLATE``    — full findings w/ CVSS, evidence, fixes
    * ``COMPLIANCE_REPORT_TEMPLATE``    — PCI-DSS / SOC 2 / ISO-IEC 27001 mapping
                                          (alias: ``COMPLIANCE_TEMPLATE``)
    * ``VULNERABILITY_TEMPLATE``        — single-vuln report (CVE-centric)
                                          (alias: ``VULNERABILITY_REPORT_TEMPLATE``)
    * ``TECHNICAL_REPORT_TEMPLATE``     — full technical / methodology report

Functions:
    * ``get_template(name)      -> str``       — look up a template by name
    * ``list_templates()        -> list[str]`` — sorted list of template names
    * ``validate_template(name) -> bool``      — membership check
    * ``render_template(tpl, ctx) -> str``     — render a template string (or
                                                  registered name) with a context

Class:
    * ``TemplateEngine``                      — stateful engine that can register
                                                 custom templates and render by
                                                 name.
"""

from __future__ import annotations

import re
from typing import Any, Dict, List, Optional

__all__: List[str] = [
    # Template strings
    "DEFAULT_TEMPLATE",
    "EXECUTIVE_SUMMARY_TEMPLATE",
    "DETAILED_FINDINGS_TEMPLATE",
    "COMPLIANCE_REPORT_TEMPLATE",
    "COMPLIANCE_TEMPLATE",
    "VULNERABILITY_TEMPLATE",
    "VULNERABILITY_REPORT_TEMPLATE",
    "TECHNICAL_REPORT_TEMPLATE",
    # Functions
    "get_template",
    "list_templates",
    "validate_template",
    "render_template",
    # Class
    "TemplateEngine",
]

# ---------------------------------------------------------------------------
# 1. Built-in template strings
# ---------------------------------------------------------------------------

DEFAULT_TEMPLATE = """\
# {title}

**Date:** {date}
**Author:** {author}
**Target:** {target}

---

## 1. Scope

{scope}

## 2. Executive Summary

{executive_summary}

## 3. Findings Overview

{findings_table}

## 4. Detailed Findings

{findings_detail}

## 5. Methodology

{methodology}

## 6. Appendices

{appendices}

## 7. Metadata

{metadata_json}

---
*Generated by SecurAgentX*
"""

EXECUTIVE_SUMMARY_TEMPLATE = """\
# Executive Summary — {engagement_name}

**Client:** {client_name}
**Date:** {date}
**Author:** {author}
**Target:** {target}

---

## Risk Profile

| Severity | Count |
|----------|-------|
| Critical | {critical_count} |
| High     | {high_count} |
| Medium   | {medium_count} |
| Low      | {low_count} |
| Info     | {info_count} |

## Engagement Overview

{executive_summary}

## Key Recommendations

{recommendations}

## Next Steps

{next_steps}

---
*Confidential — {client_name}*
"""

DETAILED_FINDINGS_TEMPLATE = """\
# Detailed Findings Report — {title}

**Date:** {date}
**Author:** {author}
**Target:** {target}

---

## 1. Scope

{scope}

## 2. Executive Summary

{executive_summary}

## 3. Findings Summary

{findings_table}

## 4. Detailed Findings

Each finding below includes a CVSS score, evidence, exploitation steps, and
remediation guidance.

{findings_detail}

## 5. Methodology

{methodology}

## 6. Appendices

{appendices}

## 7. Metadata

{metadata_json}

---
*Generated by SecurAgentX*
"""

COMPLIANCE_REPORT_TEMPLATE = """\
# Compliance Report — {title}

**Date:** {date}
**Author:** {author}
**Target:** {target}

---

## 1. Executive Summary

{executive_summary}

## 2. PCI-DSS Compliance

The following table maps identified findings to PCI-DSS v4.0 requirements.

{pci_dss_table}

## 3. SOC 2 Compliance

The following table maps identified findings to SOC 2 Trust Services Criteria.

{soc2_table}

## 4. ISO/IEC 27001 Compliance

The following table maps identified findings to ISO/IEC 27001:2022 controls.

{iso27001_table}

## 5. Detailed Findings

{findings_detail}

## 6. Methodology

{methodology}

## 7. Appendices

{appendices}

## 8. Metadata

{metadata_json}

---
*Generated by SecurAgentX*
"""

# Alias — short name for the compliance template.
COMPLIANCE_TEMPLATE = COMPLIANCE_REPORT_TEMPLATE

VULNERABILITY_TEMPLATE = """\
# Vulnerability Report — {cve_id}

## 1. Identification

| Field | Value |
|-------|-------|
| CVE ID | {cve_id} |
| Severity | {severity} |
| CVSS Score | {cvss_score} |
| CVSS Vector | {cvss_vector} |
| Affected Component | {affected_component} |
| CVE URL | {cve_url} |
| Vendor Advisory | {vendor_advisory} |
| OWASP Reference | {owasp_reference} |

## 2. Description

{description}

## 3. Impact

{impact}

## 4. Exploitation

### Exploitation Commands

{exploitation_commands}

### Evidence

{evidence}

## 5. Remediation

### Immediate Fix

{immediate_fix}

### Long-Term Fix

{long_term_fix}

### Compensating Controls

{compensating_controls}

---
*Generated by SecurAgentX*
"""

# Alias — alternate name for the vulnerability template.
VULNERABILITY_REPORT_TEMPLATE = VULNERABILITY_TEMPLATE

TECHNICAL_REPORT_TEMPLATE = """\
# Technical Report — {title}

**Date:** {date}
**Author:** {author}
**Target:** {target}

---

## 1. overview

{overview}

## 2. methodology

{methodology}

### 2.1 tools_used

{tools_used}

### 2.2 recon_summary

{recon_summary}

## 3. findings_summary

{findings_summary}

## 4. exploit_chains

{exploit_chains}

## 5. immediate_remediation

{immediate_remediation}

## 6. appendix_raw_output

{appendix_raw_output}

## 7. Detailed Findings

{findings_detail}

## 8. Metadata

{metadata_json}

---
*Generated by SecurAgentX*
"""

# ---------------------------------------------------------------------------
# 2. Template registry
# ---------------------------------------------------------------------------

# Canonical name → template string.  Several aliases are registered so that
# callers can refer to a template by either its short or its long name.
_TEMPLATES: Dict[str, str] = {
    "default": DEFAULT_TEMPLATE,
    "executive_summary": EXECUTIVE_SUMMARY_TEMPLATE,
    "exec_summary": EXECUTIVE_SUMMARY_TEMPLATE,
    "detailed_findings": DETAILED_FINDINGS_TEMPLATE,
    "detailed": DETAILED_FINDINGS_TEMPLATE,
    "compliance": COMPLIANCE_REPORT_TEMPLATE,
    "compliance_report": COMPLIANCE_REPORT_TEMPLATE,
    "vulnerability": VULNERABILITY_TEMPLATE,
    "vulnerability_report": VULNERABILITY_TEMPLATE,
    "technical": TECHNICAL_REPORT_TEMPLATE,
    "technical_report": TECHNICAL_REPORT_TEMPLATE,
}

# ---------------------------------------------------------------------------
# 3. Render helpers
# ---------------------------------------------------------------------------

# Matches ``{identifier}`` where *identifier* is a Python-style name.  We do
# **not** use :class:`string.Formatter` because it would raise on unknown
# keys, attribute access, or stray braces; the brutal test-suite requires that
# missing keys silently become empty strings and that the rendered output
# contain **no** literal ``{`` characters.
_PLACEHOLDER_RE = re.compile(r"\{([a-zA-Z_][a-zA-Z0-9_]*)\}")


def _substitute(template: str, context: Optional[Dict[str, Any]]) -> str:
    """Substitute every ``{name}`` placeholder in *template*.

    Each placeholder is replaced with ``str(context[name])`` when *name* is
    present in *context*, otherwise with an empty string.  This guarantees a
    KeyError-free render and an output free of unsubstituted ``{...}``
    markers (provided the template itself only uses ``{identifier}``
    placeholders, which all built-in templates do).
    """
    ctx: Dict[str, Any] = dict(context) if context else {}

    def _replace(match: "re.Match[str]") -> str:
        key = match.group(1)
        if key in ctx:
            value = ctx[key]
            return "" if value is None else str(value)
        return ""

    return _PLACEHOLDER_RE.sub(_replace, template)


def render_template(template: str, context: Optional[Dict[str, Any]] = None) -> str:
    """Render *template* (a template string **or** a registered name) with *context*.

    The first argument may be either:

    * the literal template string (e.g. ``VULNERABILITY_TEMPLATE``), or
    * a registered template name (e.g. ``"vulnerability"``).

    Every ``{placeholder}`` is replaced with the corresponding context value
    (coerced via ``str``) or — when absent — with an empty string.  No
    ``KeyError`` is ever raised and the result never contains an
    unsubstituted ``{...}`` marker.
    """
    if not isinstance(template, str):
        raise TypeError(
            "render_template() expected str for 'template', got "
            f"{type(template).__name__}"
        )
    # If the caller passed a registered *name*, resolve it to the template
    # string.  This keeps the function flexible: it works both as
    # ``render_template("vulnerability", ctx)`` and as
    # ``render_template(VULNERABILITY_TEMPLATE, ctx)``.
    if template in _TEMPLATES:
        template = _TEMPLATES[template]
    return _substitute(template, context)


def get_template(name: str) -> str:
    """Return the template string registered under *name*.

    Raises :class:`KeyError` if *name* is unknown.
    """
    if name not in _TEMPLATES:
        raise KeyError(
            f"Unknown template name: {name!r}. "
            f"Available: {list_templates()}"
        )
    return _TEMPLATES[name]


def list_templates() -> List[str]:
    """Return a sorted list of all registered template names (including aliases)."""
    return sorted(_TEMPLATES.keys())


def validate_template(name: str) -> bool:
    """Return ``True`` if *name* is a registered template name."""
    return name in _TEMPLATES


# ---------------------------------------------------------------------------
# 4. TemplateEngine — stateful, registerable render engine
# ---------------------------------------------------------------------------

class TemplateEngine:
    """A small stateful engine around the template registry.

    A fresh engine starts with a **copy** of the built-in registry so that
    :meth:`register_template` calls do not mutate module-level state.
    """

    def __init__(self) -> None:
        self._templates: Dict[str, str] = dict(_TEMPLATES)

    # -- registration ------------------------------------------------------

    def register_template(self, name: str, template: str) -> None:
        """Register (or overwrite) a custom template under *name*."""
        if not isinstance(name, str) or not name:
            raise ValueError("template name must be a non-empty string")
        if not isinstance(template, str):
            raise TypeError("template must be a string")
        self._templates[name] = template

    def unregister_template(self, name: str) -> bool:
        """Remove a registered template.  Returns ``True`` if it existed."""
        return self._templates.pop(name, None) is not None

    # -- queries -----------------------------------------------------------

    def get(self, name: str) -> str:
        """Return the template string for *name* (raises ``KeyError`` if unknown)."""
        if name not in self._templates:
            raise KeyError(f"Unknown template name: {name!r}")
        return self._templates[name]

    def has(self, name: str) -> bool:
        """Return ``True`` if *name* is registered in this engine."""
        return name in self._templates

    def list(self) -> List[str]:
        """Return a sorted list of template names known to this engine."""
        return sorted(self._templates.keys())

    # convenience aliases that mirror the module-level API
    def validate(self, name: str) -> bool:
        """Alias for :meth:`has`."""
        return self.has(name)

    # -- rendering ---------------------------------------------------------

    def render(self, name: str, context: Optional[Dict[str, Any]] = None) -> str:
        """Render the template registered under *name* with *context*.

        If *name* is not registered it is treated as a literal template
        string and rendered directly (matching :func:`render_template`'s
        forgiving behaviour).
        """
        template = self._templates.get(name, name)
        return _substitute(template, context)

    def render_string(self, template: str, context: Optional[Dict[str, Any]] = None) -> str:
        """Render an ad-hoc *template* string (not a registered name) with *context*."""
        return _substitute(template, context)

    # -- dunder ------------------------------------------------------------

    def __contains__(self, name: object) -> bool:
        return isinstance(name, str) and name in self._templates

    def __len__(self) -> int:
        return len(self._templates)

    def __repr__(self) -> str:  # pragma: no cover - trivial
        return f"TemplateEngine(templates={len(self._templates)})"
