"""tools/memory_profile.py — Personal AI Memory Profile (MEMORY.md)

Manages the user's private MEMORY.md file:
  - Reads the profile and injects it into the AI's system prompt
  - Auto-generates MEMORY.md on first run (from MEMORY.md.example)
  - Uses the AI to intelligently update the profile after conversations
  - Never committed to git (in .gitignore like .env)

Format: MEMORY.md uses a simple YAML-like flat format that humans
can read and manually edit at any time.
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Dict

logger = logging.getLogger("securagentx.memory_profile")

_MEMORY_FILE = Path(__file__).parent.parent / "MEMORY.md"
_EXAMPLE_FILE = Path(__file__).parent.parent / "MEMORY.md.example"


# ─────────────────────────────────────────────────────────────
# File I/O
# ─────────────────────────────────────────────────────────────


def _ensure_memory_file() -> None:
    """Create MEMORY.md from example template if it doesn't exist yet."""
    if not _MEMORY_FILE.exists():
        if _EXAMPLE_FILE.exists():
            content = _EXAMPLE_FILE.read_text(encoding="utf-8")
        else:
            content = _default_template()
        _MEMORY_FILE.write_text(content, encoding="utf-8")
        logger.info("Created fresh MEMORY.md from template")


def _default_template() -> str:
    """Fallback template if MEMORY.md.example is missing."""
    return """# MEMORY.md — Personal AI Memory Profile
# AUTO-GENERATED by SecurAgentX | Private — do NOT commit to git

## Identity
name: ""
preferred_language: ""
nickname: ""

## Communication Style
tone: ""
verbosity: ""
expertise_level: ""
preferred_format: ""

## AI Personality Adjustments
ai_should_use_emoji: ""
ai_should_explain_basics: ""
ai_humor_level: ""

## Frequent Targets & Interests
frequent_targets: []
areas_of_interest: []

## Custom Notes
notes: ""
"""


def read_memory() -> Dict[str, str]:
    """
    Read and parse MEMORY.md into a flat key → value dict.
    Ignores comment lines and empty values.
    """
    _ensure_memory_file()

    profile: Dict[str, str] = {}
    try:
        text = _MEMORY_FILE.read_text(encoding="utf-8")
        for line in text.splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            # Match: key: "value" or key: value
            m = re.match(r'^(\w[\w_ ]*?)\s*:\s*"?([^"#\n]*)"?', line)
            if m:
                key = m.group(1).strip().lower().replace(" ", "_")
                value = m.group(2).strip()
                if value and value not in ("[]", '""', "''"):
                    profile[key] = value
    except Exception as e:
        logger.warning(f"Could not read MEMORY.md: {e}")

    return profile


def write_field(key: str, value: str) -> None:
    """Update a single field in MEMORY.md."""
    _ensure_memory_file()
    try:
        text = _MEMORY_FILE.read_text(encoding="utf-8")
        pattern = rf'^({re.escape(key)}\s*:\s*)("?[^"\n]*"?)'

        new_line = f'{key}: "{value}"'
        if re.search(pattern, text, flags=re.MULTILINE | re.IGNORECASE):
            text = re.sub(pattern, new_line, text, flags=re.MULTILINE | re.IGNORECASE)
        else:
            # Append to Custom Notes section
            text += f"\n{new_line}"

        _MEMORY_FILE.write_text(text, encoding="utf-8")
        logger.debug(f"MEMORY.md updated: {key} = {value}")
    except Exception as e:
        logger.warning(f"Could not write MEMORY.md: {e}")


def append_target(target: str) -> None:
    """Add a target to the frequent_targets list if not already there."""
    _ensure_memory_file()
    try:
        text = _MEMORY_FILE.read_text(encoding="utf-8")
        if target.lower() not in text.lower():
            text = re.sub(r"(frequent_targets:\s*\[\])", f"frequent_targets:\n  - {target}", text)
            # If already a list, append
            if f"  - {target}" not in text:
                text = re.sub(r"(frequent_targets:)", f"\\1\n  - {target}", text)
            _MEMORY_FILE.write_text(text, encoding="utf-8")
    except Exception as e:
        logger.warning(f"Could not append target: {e}")


# ─────────────────────────────────────────────────────────────
# AI-Powered Profile Updates
# ─────────────────────────────────────────────────────────────


def ai_update_memory(conversation_snippet: str, ai_client=None) -> None:
    """
    Ask AI to extract personality/preference signals from the conversation
    and update MEMORY.md accordingly.

    Called silently in the background after each interaction.
    """
    if not ai_client:
        return

    current_profile = build_memory_prompt_block()
    if not current_profile:
        current_profile = "(empty — first time meeting this user)"

    prompt = f"""You are analyzing a conversation to update a user's personal memory profile.

Current profile:
{current_profile}

Recent conversation:
{conversation_snippet[:800]}

Extract ONLY clear, confident signals about the user's:
- name or nickname (if mentioned)
- preferred language (thai/english)
- communication style (casual/formal/technical/hacker)
- expertise level (beginner/intermediate/expert)
- response verbosity preference (brief/normal/detailed)
- humor preference
- any targets or topics they care about

Return ONLY a JSON object with keys to update (omit keys with no new info):
{{
  "name": "...",
  "preferred_language": "...",
  "tone": "...",
  "expertise_level": "...",
  "verbosity": "...",
  "ai_humor_level": "...",
  "notes": "..."
}}

If there's nothing new to learn, return: {{}}
"""

    try:
        from tools.universal_ai_client import AIMessage

        # Use short, cheap call
        if hasattr(ai_client, "simple_chat"):
            resp = ai_client.simple_chat(prompt)
        elif hasattr(ai_client, "chat"):
            resp = ai_client.chat([AIMessage(role="user", content=prompt)]).content
        else:
            return

        # Parse the JSON response
        import json

        # Extract JSON from response
        json_match = re.search(r"\{[^{}]*\}", resp, re.DOTALL)
        if not json_match:
            return

        updates = json.loads(json_match.group())
        if not updates:
            return

        # Apply updates to MEMORY.md
        for key, value in updates.items():
            if value and str(value).strip() and str(value) not in ("null", "None", ""):
                write_field(key, str(value))

        logger.info(f"MEMORY.md auto-updated: {list(updates.keys())}")

    except Exception as e:
        logger.debug(f"Memory update skipped: {e}")


# ─────────────────────────────────────────────────────────────
# Context Injection
# ─────────────────────────────────────────────────────────────


def build_memory_prompt_block() -> str:
    """
    Build a concise block to inject into the AI's system prompt.
    This is what the AI actually "sees" about the user before responding.
    """
    profile = read_memory()
    if not profile:
        return ""

    lines = []

    # Identity
    name = profile.get("name") or profile.get("nickname")
    if name:
        lines.append(f"User's name: {name} (always address them as '{name}')")

    # Language
    lang = profile.get("preferred_language")
    if lang:
        if "thai" in lang.lower():
            lines.append("Always respond in Thai.")
        else:
            lines.append(f"Respond in {lang}.")

    # Tone
    tone = profile.get("tone")
    expertise = profile.get("expertise_level")
    if tone:
        lines.append(f"Communication style: {tone}.")
    if expertise:
        lvl_map = {
            "beginner": "Explain things clearly with examples. Avoid jargon.",
            "intermediate": "Assume moderate familiarity. Skip basics.",
            "expert": "Be direct and technical. Skip explanations, give code/commands.",
        }
        hint = lvl_map.get(expertise.lower(), "")
        if hint:
            lines.append(f"User expertise: {expertise}. {hint}")

    # Verbosity
    verbosity = profile.get("verbosity")
    if verbosity:
        v_map = {
            "brie": "Keep responses short and to the point.",
            "detailed": "Provide thorough, detailed explanations.",
            "normal": "Use balanced response length.",
        }
        hint = v_map.get(verbosity.lower(), "")
        if hint:
            lines.append(hint)

    # Emoji
    emoji_pref = profile.get("ai_should_use_emoji", "")
    if emoji_pref.lower() == "no":
        lines.append("Do NOT use emojis in responses.")
    elif emoji_pref.lower() == "yes":
        lines.append("Feel free to use emojis occasionally.")

    # Humor
    humor = profile.get("ai_humor_level")
    if humor and humor.lower() != "none":
        lines.append(f"Humor level: {humor} — occasional light humor is welcome.")

    # Notes
    notes = profile.get("notes")
    if notes and notes not in ('""', "''"):
        lines.append(f"Special note: {notes}")

    if not lines:
        return ""

    return "=== Personal Memory Profile ===\n" + "\n".join(lines) + "\n=== End Profile ==="


def get_memory_path() -> Path:
    """Return the path to the user's MEMORY.md file."""
    return _MEMORY_FILE


def show_memory_summary() -> str:
    """Return a human-readable summary of the current memory profile."""
    profile = read_memory()
    _ensure_memory_file()

    if not profile:
        return (
            "MEMORY.md is empty. SecurAgentX will learn your preferences\n"
            "automatically as you chat.\n"
            f"File location: {_MEMORY_FILE}"
        )

    lines = [f"Memory Profile (from {_MEMORY_FILE}):"]
    for key, value in profile.items():
        lines.append(f"  {key}: {value}")
    return "\n".join(lines)
