"""
tools/reporter.py — Professional Markdown Bug Report Generator
- CVSS-style severity summary table
- Structured sections: Executive, Recon, Findings, AI Insights, Disclaimer
- Reads subdomain/live host counts from report dir
"""

from __future__ import annotations

import os
from datetime import datetime
from pathlib import Path
from typing import Dict, List


def _count_lines(filepath: str) -> int:
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            return sum(1 for line in f if line.strip())
    except Exception:
        return 0


def generate_bug_report(
    target: str,
    findings: List[Dict],
    report_path: str,
    ai_insights: str = "",
) -> str:
    """
    Generate a professional Markdown bug bounty report.
    Returns the path of the written file.
    """
    report_dir = str(Path(report_path).parent)
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC")

    # Stats from report dir
    subs_count = _count_lines(os.path.join(report_dir, f"{target}_subs.txt")) or _count_lines(
        os.path.join(report_dir, "subdomains.txt")
    )
    live_count = _count_lines(os.path.join(report_dir, "live_hosts.txt"))
    url_count = _count_lines(os.path.join(report_dir, "discovered_urls.txt"))

    # Severity counts
    by_sev: Dict[str, int] = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "INFO": 0}
    for f in findings:
        sev = f.get("severity", "INFO").upper()
        by_sev[sev] = by_sev.get(sev, 0) + 1

    content = """#  Bug Bounty Security Report

**Target:** `{target}`
**Date:** {now}
**Framework:** SecurAgentX AI Bug Bounty Framework
**Assessor:** Automated + AI-Assisted

---

## 1. Executive Summary

| Metric | Count |
|--------|-------|
| Subdomains Discovered | {subs_count} |
| Live Hosts | {live_count} |
| URLs Crawled | {url_count} |
| Total Findings | {len(findings)} |
|  Critical | {by_sev['CRITICAL']} |
|  High | {by_sev['HIGH']} |
|  Medium | {by_sev['MEDIUM']} |
|  Low | {by_sev['LOW']} |
| ℹ Info | {by_sev['INFO']} |

---

## 2. Reconnaissance Summary

- **Subdomain Enumeration:** Subfinder, Waybackurls, GAU
- **Live Host Probing:** HTTPx
- **URL Crawling:** Katana
- Subdomains file: `{report_dir}/{target}_subs.txt`
- Live hosts file: `{report_dir}/live_hosts.txt`
- URLs file: `{report_dir}/discovered_urls.txt`

---

## 3. Vulnerability Findings

"""
    if findings:
        for i, f in enumerate(findings, 1):
            content += """### {i}. {f.get('name', 'Finding')}

| Field | Value |
|-------|-------|
| **Severity** | {f.get('severity', 'N/A')} |
| **URL** | `{f.get('url', 'N/A')}` |
| **Details** | {f.get('details', 'N/A')[:200]} |

"""
    else:
        content += "_No high-severity vulnerabilities detected by automated scanning. Manual review recommended._\n\n"

    content += """---

## 4. AI Insights & Recommendations

{ai_insights if ai_insights else "_Run AI analysis via `python main.py ai` for detailed recommendations._"}

---

## 5. Disclaimer

> This report was generated for **authorized** security research and bug bounty purposes only.
> All testing was performed with explicit permission. Unauthorized testing is illegal.

---
*Generated by SecurAgentX AI Framework — {now}*
"""

    Path(report_path).write_text(content, encoding="utf-8")
    return report_path
