"""tools/vuln_reasoning.py — Deep LLM Vulnerability Reasoning Engine.

This module makes SecurAgentX a true AI vulnerability researcher rather than
a simple tool-chaining agent. It leverages the LLM's analytical capabilities
to:

1. Analyse raw tool output and extract security-relevant signals
2. Hypothesise vulnerabilities from patterns the LLM recognises
3. Correlate findings across multiple tools and steps
4. Prioritise which attack vectors to investigate next
5. Generate novel test payloads based on context
6. Reason about business logic flaws from API behaviour

The key insight: a security tool's output is raw data; the LLM's job is to
*interpret* that data, find non-obvious vulnerability patterns, and decide
what to test next — exactly what a human pentester does.
"""

from __future__ import annotations

import json
import logging
import re
import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

logger = logging.getLogger("securagentx.vuln_reasoning")


# ═══════════════════════════════════════════════════════════════════════════
# Data structures
# ═══════════════════════════════════════════════════════════════════════════


@dataclass
class VulnHypothesis:
    """A vulnerability hypothesis generated by the LLM."""

    title: str
    vuln_class: str  # e.g. "ssrf", "sqli", "xss", "auth_bypass"
    confidence: float  # 0.0 - 1.0
    reasoning: str
    evidence: List[str] = field(default_factory=list)
    suggested_tests: List[str] = field(default_factory=list)
    cwe: str = ""
    severity: str = "Medium"  # Info/Low/Medium/High/Critical
    target_endpoint: str = ""
    parameter: str = ""
    payload: str = ""


@dataclass
class AnalysisResult:
    """Result of analysing tool output."""

    hypotheses: List[VulnHypothesis] = field(default_factory=list)
    signals: List[str] = field(default_factory=list)
    next_actions: List[str] = field(default_factory=list)
    risk_assessment: str = ""
    coverage_gaps: List[str] = field(default_factory=list)
    correlations: List[str] = field(default_factory=list)
    # Chain-of-thought reasoning trace from the multi-turn analysis.
    # Each entry: {"phase": "think"|"critique", "content": "..."}
    # Useful for TUI display / debugging / audit trail of *how* the AI
    # arrived at its hypotheses, not just what they are.
    reasoning_trace: List[Dict[str, str]] = field(default_factory=list)


# ═══════════════════════════════════════════════════════════════════════════
# Reasoning prompts
# ═══════════════════════════════════════════════════════════════════════════


_ANALYSIS_SYSTEM_PROMPT = """You are an elite security researcher analysing tool output.
Your job is to find vulnerabilities that the tool itself cannot detect —
patterns, correlations, and logic flaws that require human-like reasoning.

Think like a senior penetration tester:
- What does this output tell us about the application's security posture?
- What attack vectors are now MORE likely given what we've learned?
- What parameters or endpoints look suspicious?
- Are there any information disclosures that could be chained?
- What business logic flaws might exist based on the API structure?
- What should we test NEXT to confirm or rule out hypotheses?

Be specific and actionable. Every hypothesis must include a concrete test."""


_HYPOTHESIS_PROMPT_TEMPLATE = """Analyze the following tool output and generate vulnerability hypotheses.

## Target: {target}
## Tool: {tool_name}
## Raw Output:
{tool_output}

## Previous Findings (from earlier steps):
{previous_findings}

## Tech Stack Detected:
{tech_stack}

## Task:
Generate vulnerability hypotheses as JSON. For each hypothesis:
1. Identify the vulnerability CLASS (ssrf, sqli, xss, auth_bypass, idor, race_condition, etc.)
2. Explain your REASONING — why does this output suggest this vulnerability?
3. List concrete EVIDENCE from the output
4. Suggest specific TESTS to confirm (payloads, endpoints, parameters)
5. Rate your CONFIDENCE (0.0-1.0)
6. Assign a SEVERITY (Info/Low/Medium/High/Critical)

Return JSON:
{{
  "hypotheses": [
    {{
      "title": "...",
      "vuln_class": "...",
      "confidence": 0.0,
      "reasoning": "...",
      "evidence": ["..."],
      "suggested_tests": ["..."],
      "cwe": "CWE-XXX",
      "severity": "Medium",
      "target_endpoint": "...",
      "parameter": "...",
      "payload": "..."
    }}
  ],
  "signals": ["security-relevant signals detected"],
  "next_actions": ["what to test next"],
  "risk_assessment": "overall risk summary",
  "coverage_gaps": ["what we haven't tested yet"]
}}"""


# ── Chain-of-thought prompts (multi-turn reasoning) ─────────────────────────
# These drive the 3-turn reasoning loop in VulnReasoningEngine.analyze_output.
# Turn 1: free-form thinking — no JSON, just reason.
# Turn 2: self-critique of that thinking.
# Turn 3: structured hypotheses (using _HYPOTHESIS_PROMPT_TEMPLATE above).

_COT_THINK_PROMPT = """Before producing any findings, think step-by-step about this
tool output. This is a *reasoning* turn — do NOT output JSON yet.

## Target: {target}
## Tool: {tool_name}
## Raw Output:
{tool_output}

## Previous Findings:
{previous_findings}

## Tech Stack:
{tech_stack}

Reason about:
1. What does this output actually tell us? (signals, anomalies, surprises)
2. What assumptions is the application making that we could violate?
3. What attack vectors are NOW more likely than they were before this output?
4. What endpoints/parameters look interesting and why?
5. What is the single most promising next probe — and what would the
   result tell us?

Write your reasoning as plain prose. Be specific. Cite line evidence.
"""


_COT_CRITIQUE_PROMPT = """Now critically review your own reasoning above.

- Which of your hypotheses are weakly supported? Mark them and say why.
- What did you MISS? Think about edge cases, encoding, race conditions,
  trust boundaries, and business-logic flaws that do not show up in
  scanner output.
- Which hypothesis would a *senior* pentester challenge you on?
- If the most likely hypothesis turns out to be wrong, what is the
  fallback probe?

Reply as plain prose. Do NOT output JSON yet. Be honest about gaps.
"""




_PAYLOAD_GEN_PROMPT = """You are a payload generation expert. Given the context below,
generate targeted test payloads that are likely to find vulnerabilities.

## Vulnerability Class: {vuln_class}
## Target Endpoint: {endpoint}
## Parameter: {parameter}
## Tech Stack: {tech_stack}
## Known Context: {context}
## Previous Attempts: {previous_attempts}

Generate 5-10 creative payloads. Think about:
- WAF bypass techniques (encoding, case variation, alternative syntax)
- Tech-stack-specific payloads (framework-specific injection)
- Chained payloads that combine multiple techniques
- payloads that exploit the specific parameter's expected behavior

Return JSON:
{{
  "payloads": [
    {{
      "payload": "...",
      "technique": "...",
      "expected_behavior": "what to look for in the response",
      "bypass_strategy": "how it evades WAF/filters"
    }}
  ]
}}"""


_CORRELATION_PROMPT = """You are correlating findings from multiple security tools.
Find attack chains and escalation paths that individual tools missed.

## All Findings:
{all_findings}

## All Hypotheses:
{all_hypotheses}

## Tech Stack:
{tech_stack}

## Task:
Find correlations — chains of vulnerabilities that, when combined,
create a more severe attack path than any individual finding.

Return JSON:
{{
  "chains": [
    {{
      "title": "...",
      "description": "how the chain works",
      "steps": ["finding1 -> finding2 -> impact"],
      "combined_severity": "Critical",
      "exploitation_path": "step by step exploitation"
    }}
  ],
  "escalation_paths": [
    "how a Low finding could be escalated to High/Critical"
  ]
}}"""


# ═══════════════════════════════════════════════════════════════════════════
# VulnReasoningEngine
# ═══════════════════════════════════════════════════════════════════════════


class VulnReasoningEngine:
    """Deep LLM vulnerability reasoning engine.

    This is NOT a tool runner — it's an analytical layer that sits between
    tool execution and action selection. It makes the LLM actively reason
    about what the tools found and what to test next.

    Usage:
        engine = VulnReasoningEngine(client)
        result = engine.analyze_output(
            target="example.com",
            tool_name="ssrf_scanner",
            tool_output="...",
            previous_findings=[...],
            tech_stack={"server": "nginx", "language": "python"},
        )
        for hyp in result.hypotheses:
            print(f"{hyp.title} (confidence={hyp.confidence})")
    """

    def __init__(self, client: Any = None, temperature: float = 0.3) -> None:
        """Initialize the reasoning engine.

        Args:
            client: An LLM client (AIClientManager or UniversalAIClient).
            temperature: LLM temperature for reasoning calls (lower = more
                deterministic, but 0.3 allows some creative hypothesis generation).
        """
        self.client = client
        self.temperature = temperature
        self._analysis_cache: Dict[str, AnalysisResult] = {}

    def analyze_output(
        self,
        target: str,
        tool_name: str,
        tool_output: str,
        previous_findings: Optional[List[Dict]] = None,
        tech_stack: Optional[Dict[str, Any]] = None,
    ) -> AnalysisResult:
        """Analyze raw tool output and generate vulnerability hypotheses.

        This is the core method — it asks the LLM to reason about what the
        tool found, not just parse its output.

        Uses a *chain-of-thought* reasoning pattern (multi-turn) so the
        model thinks step-by-step, critiques its own hypotheses, and
        only then produces structured output — instead of jumping straight
        to JSON in a single shot. This significantly improves hypothesis
        quality on complex targets (analogous to ReAct / self-critique
        patterns in modern agent design).

        Args:
            target: The target being scanned.
            tool_name: Name of the tool that produced the output.
            tool_output: Raw tool output text.
            previous_findings: Findings from previous steps (for correlation).
            tech_stack: Detected technology stack.

        Returns:
            AnalysisResult with hypotheses, signals, and next actions.
        """
        if not self.client:
            logger.warning("No LLM client — falling back to heuristic analysis")
            return self._heuristic_analysis(target, tool_name, tool_output, previous_findings or [])

        # Truncate output to fit context window
        max_output = 4000
        truncated_output = tool_output[:max_output]
        if len(tool_output) > max_output:
            truncated_output += "\n... [truncated]"

        findings_str = json.dumps(previous_findings or [], indent=2, default=str)[:2000]
        tech_str = json.dumps(tech_stack or {}, indent=2, default=str)

        # ── Chain-of-thought reasoning (3 turns) ──
        # Turn 1: Think step-by-step about what the output tells us.
        # Turn 2: Critique the first-pass thinking — what's missing / weak?
        # Turn 3: Produce structured JSON hypotheses with the critique in mind.
        try:
            from tools.universal_ai_client import AIMessage

            # Use explicit message lists per turn (not a shared mutable list)
            # so each chat() call receives only the messages we intend.
            think_messages = [
                AIMessage(role="system", content=_ANALYSIS_SYSTEM_PROMPT),
                AIMessage(role="user", content=_COT_THINK_PROMPT.format(
                    target=target,
                    tool_name=tool_name,
                    tool_output=truncated_output,
                    previous_findings=findings_str,
                    tech_stack=tech_str,
                )),
            ]
            think_response = self.client.chat(think_messages, temperature=self.temperature)
            thinking = (think_response.content or "").strip()
            if not thinking:
                logger.debug("chain-of-thought turn 1 empty — falling back")
                return self._heuristic_analysis(target, tool_name, tool_output, previous_findings or [])

            # Turn 2: self-critique (carries turn 1 as assistant context)
            critique_messages = [
                AIMessage(role="system", content=_ANALYSIS_SYSTEM_PROMPT),
                AIMessage(role="user", content=_COT_THINK_PROMPT.format(
                    target=target,
                    tool_name=tool_name,
                    tool_output=truncated_output,
                    previous_findings=findings_str,
                    tech_stack=tech_str,
                )),
                AIMessage(role="assistant", content=thinking),
                AIMessage(role="user", content=_COT_CRITIQUE_PROMPT),
            ]
            critique_response = self.client.chat(critique_messages, temperature=self.temperature)
            critique = (critique_response.content or "").strip()

            # Turn 3: structured hypotheses grounded in thinking + critique
            final_messages = [
                AIMessage(role="system", content=_ANALYSIS_SYSTEM_PROMPT),
                AIMessage(role="user", content=_COT_THINK_PROMPT.format(
                    target=target,
                    tool_name=tool_name,
                    tool_output=truncated_output,
                    previous_findings=findings_str,
                    tech_stack=tech_str,
                )),
                AIMessage(role="assistant", content=thinking),
                AIMessage(role="user", content=_COT_CRITIQUE_PROMPT),
                AIMessage(role="assistant", content=critique),
                AIMessage(role="user", content=_HYPOTHESIS_PROMPT_TEMPLATE.format(
                    target=target,
                    tool_name=tool_name,
                    tool_output=truncated_output,
                    previous_findings=findings_str,
                    tech_stack=tech_str,
                )),
            ]
            response = self.client.chat(final_messages, temperature=self.temperature)
            result = self._parse_analysis(response.content or "")
            # Attach reasoning trace for downstream observability (TUI / logs).
            try:
                result.reasoning_trace = [
                    {"phase": "think", "content": thinking},
                    {"phase": "critique", "content": critique},
                ]
            except Exception:
                pass
            return result
        except Exception as e:
            logger.error("LLM analysis failed: %s", e)
            return self._heuristic_analysis(target, tool_name, tool_output, previous_findings or [])

    def generate_payloads(
        self,
        vuln_class: str,
        endpoint: str,
        parameter: str,
        tech_stack: Dict[str, Any],
        context: str = "",
        previous_attempts: Optional[List[str]] = None,
    ) -> List[Dict[str, str]]:
        """Generate targeted test payloads for a specific vulnerability class.

        The LLM generates creative, context-aware payloads — not just a
        static wordlist. This adapts to the tech stack and previous results.

        Args:
            vuln_class: e.g. "ssrf", "sqli", "xss", "ssti"
            endpoint: The target endpoint URL.
            parameter: The parameter to test.
            tech_stack: Detected technology stack.
            context: Additional context about the target.
            previous_attempts: Payloads already tried (to avoid repeats).

        Returns:
            List of payload dicts with 'payload', 'technique',
            'expected_behavior', and 'bypass_strategy' keys.
        """
        if not self.client:
            return self._fallback_payloads(vuln_class)

        prompt = _PAYLOAD_GEN_PROMPT.format(
            vuln_class=vuln_class,
            endpoint=endpoint,
            parameter=parameter,
            tech_stack=json.dumps(tech_stack, default=str),
            context=context[:500],
            previous_attempts=json.dumps(previous_attempts or [], default=str)[:500],
        )

        try:
            from tools.universal_ai_client import AIMessage

            response = self.client.chat(
                [
                    AIMessage(role="system", content="You are a payload generation expert."),
                    AIMessage(role="user", content=prompt),
                ],
                temperature=0.4,  # slightly higher for creativity
            )
            data = self._extract_json(response.content or "")
            return data.get("payloads", []) if data else self._fallback_payloads(vuln_class)
        except Exception as e:
            logger.error("Payload generation failed: %s", e)
            return self._fallback_payloads(vuln_class)

    def correlate_findings(
        self,
        all_findings: List[Dict],
        all_hypotheses: List[VulnHypothesis],
        tech_stack: Dict[str, Any],
    ) -> Dict[str, Any]:
        """Correlate findings from multiple tools to find attack chains.

        This is where the LLM's reasoning shines — it can see connections
        between findings that rule-based systems miss.

        Args:
            all_findings: All findings from all tools.
            all_hypotheses: All hypotheses generated so far.
            tech_stack: Detected technology stack.

        Returns:
            Dict with 'chains', 'escalation_paths', and 'combined_risk'.
        """
        if not self.client:
            return {"chains": [], "escalation_paths": [], "combined_risk": "Unknown"}

        findings_str = json.dumps(all_findings[:20], indent=2, default=str)[:3000]
        hyps_str = json.dumps(
            [
                {"title": h.title, "vuln_class": h.vuln_class, "confidence": h.confidence}
                for h in all_hypotheses[:20]
            ],
            indent=2,
        )[:2000]
        tech_str = json.dumps(tech_stack, default=str)

        prompt = _CORRELATION_PROMPT.format(
            all_findings=findings_str,
            all_hypotheses=hyps_str,
            tech_stack=tech_str,
        )

        try:
            from tools.universal_ai_client import AIMessage

            response = self.client.chat(
                [
                    AIMessage(role="system", content=_ANALYSIS_SYSTEM_PROMPT),
                    AIMessage(role="user", content=prompt),
                ],
                temperature=self.temperature,
            )
            return self._extract_json(response.content or "") or {
                "chains": [],
                "escalation_paths": [],
                "combined_risk": "Unknown",
            }
        except Exception as e:
            logger.error("Correlation failed: %s", e)
            return {"chains": [], "escalation_paths": [], "combined_risk": "Unknown"}

    def prioritize_hypotheses(
        self,
        hypotheses: List[VulnHypothesis],
        max_actions: int = 5,
    ) -> List[VulnHypothesis]:
        """Prioritize hypotheses by potential impact and confidence.

        Uses a scoring formula: score = confidence * severity_weight * novelty.
        """
        severity_weights = {
            "Critical": 5.0,
            "High": 4.0,
            "Medium": 2.5,
            "Low": 1.5,
            "Info": 0.5,
        }

        def score(h: VulnHypothesis) -> float:
            sev = severity_weights.get(h.severity, 1.0)
            return h.confidence * sev

        return sorted(hypotheses, key=score, reverse=True)[:max_actions]

    # ═══════════════════════════════════════════════════════════════════════════
    # Internal helpers
    # ═══════════════════════════════════════════════════════════════════════════

    def _parse_analysis(self, response_text: str) -> AnalysisResult:
        """Parse LLM response into AnalysisResult."""
        data = self._extract_json(response_text)
        if not data:
            return AnalysisResult()

        hypotheses: List[VulnHypothesis] = []
        for h in data.get("hypotheses", []):
            try:
                hypotheses.append(
                    VulnHypothesis(
                        title=h.get("title", ""),
                        vuln_class=h.get("vuln_class", ""),
                        confidence=float(h.get("confidence", 0.5)),
                        reasoning=h.get("reasoning", ""),
                        evidence=h.get("evidence", []),
                        suggested_tests=h.get("suggested_tests", []),
                        cwe=h.get("cwe", ""),
                        severity=h.get("severity", "Medium"),
                        target_endpoint=h.get("target_endpoint", ""),
                        parameter=h.get("parameter", ""),
                        payload=h.get("payload", ""),
                    )
                )
            except Exception as e:
                logger.debug("Failed to parse hypothesis: %s", e)

        return AnalysisResult(
            hypotheses=hypotheses,
            signals=data.get("signals", []),
            next_actions=data.get("next_actions", []),
            risk_assessment=data.get("risk_assessment", ""),
            coverage_gaps=data.get("coverage_gaps", []),
            correlations=data.get("correlations", []),
        )

    @staticmethod
    def _extract_json(text: str) -> Optional[Dict]:
        """Extract JSON from LLM response (handles markdown fences)."""
        try:
            from securagentx.scanning.helpers import extract_json

            result = extract_json(text, expect="object")
            return result if isinstance(result, dict) else None
        except ImportError:
            # Fallback: simple regex extraction
            # Try fenced JSON first
            m = re.search(r"```(?:json)?\s*\n?(.*?)\n?```", text, re.DOTALL)
            if m:
                try:
                    return json.loads(m.group(1))
                except json.JSONDecodeError:
                    pass
            # Try raw JSON
            m = re.search(r"\{[\s\S]*\}", text)
            if m:
                try:
                    return json.loads(m.group(0))
                except json.JSONDecodeError:
                    pass
            return None

    def _heuristic_analysis(
        self,
        target: str,
        tool_name: str,
        tool_output: str,
        previous_findings: List[Dict],
    ) -> AnalysisResult:
        """Fallback heuristic analysis when no LLM client is available.

        Uses pattern matching to find common vulnerability signals.
        """
        signals: List[str] = []
        hypotheses: List[VulnHypothesis] = []
        output_lower = tool_output.lower()

        # Check for common vulnerability signals
        patterns: List[Tuple[str, str, str, float, str]] = [
            (
                r"sql|mysql|postgres|syntax error|union select",
                "sqli",
                "SQL error message detected — possible SQL injection",
                0.6,
                "CWE-89",
            ),
            (
                r"stack trace|traceback|exception|error 500",
                "info_disclosure",
                "Stack trace detected — information disclosure",
                0.5,
                "CWE-209",
            ),
            (
                r"redirect|location:|302|301",
                "open_redirect",
                "Redirect detected — check for open redirect",
                0.4,
                "CWE-601",
            ),
            (
                r"cookie|session|set-cookie",
                "session",
                "Session cookie detected — check for fixation/fixation",
                0.3,
                "CWE-384",
            ),
            (
                r"cors|access-control-allow-origin",
                "cors",
                "CORS header detected — check for misconfiguration",
                0.5,
                "CWE-942",
            ),
            (
                r"jwt|bearer|token",
                "auth",
                "Authentication token detected — check for JWT weaknesses",
                0.4,
                "CWE-287",
            ),
            (
                r"upload|file|attachment",
                "file_upload",
                "File upload endpoint — check for unrestricted upload",
                0.5,
                "CWE-434",
            ),
            (
                r"admin|dashboard|panel",
                "auth_bypass",
                "Admin path detected — check for auth bypass",
                0.5,
                "CWE-285",
            ),
            (
                r"api|json|rest",
                "api_abuse",
                "API endpoint detected — check for rate limiting/IDOR",
                0.4,
                "CWE-639",
            ),
            (
                r"debug|test|dev|staging",
                "info_disclosure",
                "Debug/test endpoint detected — may expose sensitive info",
                0.6,
                "CWE-489",
            ),
        ]

        for pattern, vuln_class, reasoning, confidence, cwe in patterns:
            if re.search(pattern, output_lower):
                signals.append(f"{vuln_class}: pattern detected in {tool_name} output")
                hypotheses.append(
                    VulnHypothesis(
                        title=f"Potential {vuln_class} on {target}",
                        vuln_class=vuln_class,
                        confidence=confidence,
                        reasoning=reasoning,
                        evidence=[f"Pattern matched in {tool_name} output"],
                        suggested_tests=[f"Test {vuln_class} payloads against {target}"],
                        cwe=cwe,
                        severity="Medium" if confidence > 0.4 else "Low",
                        target_endpoint=target,
                    )
                )

        next_actions = list(set(h.suggested_tests[0] for h in hypotheses if h.suggested_tests))[:5]

        return AnalysisResult(
            hypotheses=hypotheses,
            signals=signals,
            next_actions=next_actions,
            risk_assessment=f"Heuristic analysis found {len(hypotheses)} potential issues",
            coverage_gaps=["Full LLM analysis unavailable — install API key for deep reasoning"],
        )

    def _fallback_payloads(self, vuln_class: str) -> List[Dict[str, str]]:
        """Return static fallback payloads when LLM is unavailable."""
        fallbacks: Dict[str, List[Dict[str, str]]] = {
            "ssrf": [
                {
                    "payload": "http://169.254.169.254/latest/meta-data/",
                    "technique": "AWS metadata",
                    "expected_behavior": "metadata response",
                    "bypass_strategy": "none",
                },
                {
                    "payload": "http://localhost:80",
                    "technique": "localhost",
                    "expected_behavior": "internal service",
                    "bypass_strategy": "none",
                },
                {
                    "payload": "http://0x7f000001",
                    "technique": "hex encoding",
                    "expected_behavior": "internal service",
                    "bypass_strategy": "hex bypass",
                },
                {
                    "payload": "http://[::1]",
                    "technique": "IPv6 localhost",
                    "expected_behavior": "internal service",
                    "bypass_strategy": "IPv6 bypass",
                },
                {
                    "payload": "gopher://localhost:6379/_FLUSHALL",
                    "technique": "gopher protocol",
                    "expected_behavior": "Redis response",
                    "bypass_strategy": "protocol smuggling",
                },
            ],
            "sqli": [
                {
                    "payload": "' OR '1'='1",
                    "technique": "boolean-based",
                    "expected_behavior": "different response",
                    "bypass_strategy": "none",
                },
                {
                    "payload": "' UNION SELECT NULL--",
                    "technique": "union-based",
                    "expected_behavior": "extra column",
                    "bypass_strategy": "none",
                },
                {
                    "payload": "1; WAITFOR DELAY '0:0:5'--",
                    "technique": "time-based",
                    "expected_behavior": "5s delay",
                    "bypass_strategy": "none",
                },
                {
                    "payload": "'/**/OR/**/1=1--",
                    "technique": "comment bypass",
                    "expected_behavior": "different response",
                    "bypass_strategy": "WAF bypass",
                },
            ],
            "xss": [
                {
                    "payload": "<script>alert(1)</script>",
                    "technique": "basic",
                    "expected_behavior": "alert popup",
                    "bypass_strategy": "none",
                },
                {
                    "payload": "<img src=x onerror=alert(1)>",
                    "technique": "event handler",
                    "expected_behavior": "alert popup",
                    "bypass_strategy": "tag variation",
                },
                {
                    "payload": "<svg onload=alert(1)>",
                    "technique": "SVG",
                    "expected_behavior": "alert popup",
                    "bypass_strategy": "tag variation",
                },
                {
                    "payload": "javascript:alert(1)",
                    "technique": "URL scheme",
                    "expected_behavior": "alert popup",
                    "bypass_strategy": "protocol bypass",
                },
            ],
            "ssti": [
                {
                    "payload": "{{7*7}}",
                    "technique": "Jinja2",
                    "expected_behavior": "49",
                    "bypass_strategy": "none",
                },
                {
                    "payload": "${7*7}",
                    "technique": "FreeMarker",
                    "expected_behavior": "49",
                    "bypass_strategy": "none",
                },
                {
                    "payload": "#{7*7}",
                    "technique": "Ruby ERB",
                    "expected_behavior": "49",
                    "bypass_strategy": "none",
                },
                {
                    "payload": "{{config}}",
                    "technique": "Jinja2 config",
                    "expected_behavior": "config dump",
                    "bypass_strategy": "none",
                },
            ],
        }
        return fallbacks.get(
            vuln_class.lower(),
            [
                {
                    "payload": "test",
                    "technique": "basic",
                    "expected_behavior": "normal response",
                    "bypass_strategy": "none",
                },
            ],
        )


# ═══════════════════════════════════════════════════════════════════════════
# Integration helper
# ═══════════════════════════════════════════════════════════════════════════


def create_reasoning_engine(client: Any = None) -> VulnReasoningEngine:
    """Create a VulnReasoningEngine with the given client.

    Args:
        client: An LLM client. If None, the engine will use heuristic
            fallback analysis.

    Returns:
        A configured VulnReasoningEngine.
    """
    return VulnReasoningEngine(client=client)
