"""tools/waf_detector.py — M9: Smart WAF Detector (probe-based).

Detects WAFs (Web Application Firewalls) by sending specific probe
requests and analyzing the response patterns, NOT by matching regex
on headers (which produces false positives from CDN headers like
"server: cloudflare" even when there's no actual WAF behavior).

Probe strategy:
  1. Baseline request (legitimate URL)
  2. Malicious-looking-but-benign payload (e.g. "UNION SELECT NULL--")
  3. SQLi trigger (single quote in param)
  4. XSS trigger (<script> in param)
  5. Path traversal trigger (../../etc/passwd)
  6. Compare responses:
     - If trigger responses are blocked but baseline works = WAF
     - Specific block responses identify specific WAFs:
       - Cloudflare: "Attention Required!" or 403 + cf-ray
       - AWS WAF: "Forbidden" + x-amzn-RequestId
       - Akamai: "Reference #" pattern
       - ModSecurity: "Not Acceptable!" or specific rule IDs
       - Sucuri: "Access Denied - Sucuri Website Firewall"
       - Wordfence: "Your access to this site has been limited"
       - Generic: 403/406/429 with no body diff

Public API:
    WAFSignature  - one detected WAF
    WAFProbeResult - full result of probing
    SmartWAFDetector:
        probe(url) -> WAFProbeResult
        suggest_evasion(waf_signature) -> List[str]
"""

from __future__ import annotations

import logging
import re
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass, field
from typing import Any, Dict, List, Tuple

from securagentx.utils.url import validate_url_scheme

logger = logging.getLogger("securagentx.waf_detector")


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class WAFSignature:
    """One WAF detection signature (block pattern + metadata)."""

    name: str  # "cloudflare", "aws_waf", etc.
    block_status: int  # typical block status
    body_pattern: Any  # regex of typical block page (compiled or string)
    header_patterns: Dict[str, Any]  # header -> regex (compiled or string)
    confidence_threshold: float = 0.7


@dataclass
class WAFProbeResult:
    """Result of probing a target for WAF presence."""

    target: str
    waf_detected: bool
    waf_name: str  # "cloudflare" / "none" / "unknown"
    confidence: float
    blocked_payloads: List[str]  # which probes got blocked
    passed_payloads: List[str]  # which probes passed (WAF bypassed)
    signature_hits: List[str]  # which signatures matched
    baseline_status: int
    suggested_evasions: List[str] = field(default_factory=list)
    raw_responses: Dict[str, Dict[str, Any]] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# WAF signatures
# ---------------------------------------------------------------------------


WAF_SIGNATURES: List[WAFSignature] = [
    WAFSignature(
        name="cloudflare",
        block_status=403,
        body_pattern=r"(Attention Required|Cloudflare|Ray ID:|cf-ray)",
        header_patterns={"server": r"cloudflare", "cf-ray": r".+"},
        confidence_threshold=0.7,
    ),
    WAFSignature(
        name="aws_waf",
        block_status=403,
        body_pattern=r"(AWS WAF|RequestId|x-amzn-)",
        header_patterns={"x-amzn-requestid": r".+", "x-amz-cf-id": r".+"},
        confidence_threshold=0.7,
    ),
    WAFSignature(
        name="akamai",
        block_status=403,
        body_pattern=r"(Reference #|AkamaiGHost|Akamai)",
        header_patterns={"server": r"AkamaiGHost"},
        confidence_threshold=0.7,
    ),
    WAFSignature(
        name="modsecurity",
        block_status=406,
        body_pattern=r"(Not Acceptable|mod_security|ModSecurity|OWASP CRS)",
        header_patterns={"server": r"Mod_Security|mod_security"},
        confidence_threshold=0.6,
    ),
    WAFSignature(
        name="sucuri",
        block_status=403,
        body_pattern=r"(Access Denied - Sucuri|Sucuri Website Firewall)",
        header_patterns={"server": r"Sucuri"},
        confidence_threshold=0.8,
    ),
    WAFSignature(
        name="wordfence",
        block_status=403,
        body_pattern=r"(Your access to this site has been limited|wordfence|generated by Wordfence)",
        header_patterns={},
        confidence_threshold=0.8,
    ),
    WAFSignature(
        name="imperva",
        block_status=403,
        body_pattern=r"(Incapsula|imperva|security incident)",
        header_patterns={"x-iinfo": r".+"},
        confidence_threshold=0.7,
    ),
    WAFSignature(
        name="f5_bigip",
        block_status=403,
        body_pattern=r"(The requested URL was rejected|F5|BIG-IP)",
        header_patterns={"server": r"BigIP|BIG-IP"},
        confidence_threshold=0.7,
    ),
    WAFSignature(
        name="barracuda",
        block_status=403,
        body_pattern=r"(Barracuda|barra)",  # case-insensitive flag
        header_patterns={},
        confidence_threshold=0.6,
    ),
    WAFSignature(
        name="generic_block",
        block_status=403,
        body_pattern=r"(blocked|forbidden|access denied|not acceptable)",
        header_patterns={},
        confidence_threshold=0.5,
    ),
]


# ---------------------------------------------------------------------------
# WAF detector
# ---------------------------------------------------------------------------


# Probe payloads designed to trigger WAFs without being destructive
# (no actual SQL injection, just patterns that WAFs are trained to detect)
WAF_PROBE_PAYLOADS = [
    ("sqli", "' OR '1'='1"),
    ("xss", "<script>alert(1)</script>"),
    ("traversal", "../../../../etc/passwd"),
    ("rce", "; ls -la"),
    ("xxe", "<!ENTITY xxe SYSTEM 'file:///etc/passwd'>"),
    ("benign_obvious", "AAAA"),  # control: not malicious at all
]


EVASION_TECHNIQUES = {
    "cloudflare": [
        "Use case variation: <ScRiPt> instead of <script>",
        "URL-encode special chars: %3Cscript%3E",
        "Double-URL-encode: %253Cscript%253E",
        "Use HTML entities: &#60;script&#62;",
        "Insert null bytes: <scr\\x00ipt>",
        "Use Unicode homoglyphs: ＜script＞ (fullwidth)",
    ],
    "aws_waf": [
        "Comment-injection: /**/UNION/**/SELECT",
        "HPP (HTTP Parameter Pollution): ?id=1&id=' OR 1=1--",
        "Use // comment: ' OR 1=1--//",
        "Tautology variation: ' OR 2>1--",
        "Time-based: ' AND SLEEP(5)--",
    ],
    "akamai": [
        "Path parameter injection: /search;payload=.../",
        "Unicode normalization: %C0%AE%C0%AE/",
        "Comment nesting: /*/**/*/",
    ],
    "modsecurity": [
        "Use MySQL comments: /*!UNION*/SELECT",
        "Hex-encoding: 0x53454c454354",
        "Whitespace substitution: %09, %0a, %0d",
        "Mixed case: UnIoN SeLeCt",
    ],
    "sucuri": [
        "Double-encoding: %2527",
        "Null-byte termination: %00<script>",
    ],
    "wordfence": [
        "WAF bypass via legitimate user-agent spoofing",
        "Slow down requests to avoid rate-based detection",
    ],
    "imperva": [
        "Rotate User-Agent every few requests",
        "Use mobile UA from known bot whitelist",
    ],
    "generic_block": [
        "Try payload mutation: <sCrIpT> instead of <script>",
        "URL-encode all special chars",
        "Use case variation: UnIoN SeLeCt",
    ],
}


class SmartWAFDetector:
    """Detects WAFs by sending probe payloads and analyzing responses."""

    def __init__(self, timeout_seconds: float = 8.0):
        self.timeout = timeout_seconds
        # Pre-compile regexes
        self._compiled_signatures = []
        for sig in WAF_SIGNATURES:
            compiled = WAFSignature(
                name=sig.name,
                block_status=sig.block_status,
                body_pattern=(
                    re.compile(sig.body_pattern, re.IGNORECASE) if sig.body_pattern else None
                ),
                header_patterns={
                    k: re.compile(v, re.IGNORECASE) for k, v in sig.header_patterns.items()
                },
                confidence_threshold=sig.confidence_threshold,
            )
            self._compiled_signatures.append(compiled)

    def _send(self, url: str) -> Dict[str, Any]:
        """Send a GET request, return response info."""
        validate_url_scheme(url)
        req = urllib.request.Request(
            url, method="GET", headers={"User-Agent": "SecurAgentX-WAF-Probe/1.0"}
        )
        try:
            with urllib.request.urlopen(req, timeout=self.timeout) as resp:  # nosec B310
                raw = resp.read(4096)
                return {
                    "status": resp.status,
                    "body": raw.decode("utf-8", errors="replace"),
                    "headers": {k.lower(): v for k, v in resp.headers.items()},
                }
        except urllib.error.HTTPError as e:
            raw = b""
            if hasattr(e, "read"):
                try:
                    raw = e.read(4096)
                except Exception as e:
                    logger.debug("Suppressed Exception: %s", e)
            return {
                "status": e.code,  # type: ignore[misc]
                "body": raw.decode("utf-8", errors="replace"),
                "headers": {k.lower(): v for k, v in (e.headers.items() if e.headers else [])},  # type: ignore[misc]
            }
        except Exception as e:
            return {"status": -1, "body": str(e), "headers": {}}

    def _payloads_with_param(self, base_url: str) -> List[Tuple[str, str]]:
        """Build (label, full_url) tuples for each probe payload."""
        _parsed = urllib.parse.urlparse(base_url)
        results = []
        for label, payload in WAF_PROBE_PAYLOADS:
            # Inject as 'q' param
            params = {"q": payload}
            qs = urllib.parse.urlencode(params)
            if "?" in base_url:
                sep = "&"
            else:
                sep = "?"
            results.append((label, f"{base_url}{sep}{qs}"))
        return results

    def _match_signatures(
        self,
        status: int,
        body: str,
        headers: Dict[str, str],
    ) -> List[str]:
        """Find all WAF signatures matching this response."""
        hits = []
        for sig in self._compiled_signatures:
            confidence = 0.0
            # Check body pattern
            if sig.body_pattern and sig.body_pattern.search(body):
                confidence += 0.5
            # Check header patterns
            for header_name, header_re in sig.header_patterns.items():
                actual = headers.get(header_name, "")
                if actual and header_re.search(actual):
                    confidence += 0.4
            # Status code match
            if status == sig.block_status:
                confidence += 0.1
            if confidence >= sig.confidence_threshold:
                hits.append(sig.name)
        return hits

    def probe(self, target: str) -> WAFProbeResult:
        """Probe a target URL for WAF presence and identify the WAF.

        Sends multiple probe payloads and compares responses. A WAF is
        detected when:
          - Baseline request succeeds (200/301/302)
          - Malicious-looking payloads get blocked (403/406/429)
        """
        # 1. Baseline
        baseline_resp = self._send(target)
        baseline_status = baseline_resp["status"]

        # 2. Probe with each payload
        raw_responses: Dict[str, Dict[str, Any]] = {}
        blocked: List[str] = []
        passed: List[str] = []
        signature_hits: List[str] = []

        for label, url in self._payloads_with_param(target):
            resp = self._send(url)
            raw_responses[label] = resp
            if resp["status"] in (403, 406, 429, 503):
                blocked.append(label)
                # Match signatures
                hits = self._match_signatures(resp["status"], resp["body"], resp["headers"])
                for h in hits:
                    if h not in signature_hits:
                        signature_hits.append(h)
            else:
                passed.append(label)

        # 3. Decide
        waf_detected = len(blocked) > 0
        waf_name = "none"
        confidence = 0.0
        if waf_detected:
            if signature_hits:
                waf_name = signature_hits[0]  # use top hit
                confidence = 0.9
            else:
                # Block happened but no signature matched — generic WAF
                waf_name = "generic_block"
                confidence = 0.5 + (len(blocked) / len(WAF_PROBE_PAYLOADS)) * 0.3

        # 4. Suggest evasions
        suggested = EVASION_TECHNIQUES.get(waf_name, [])

        return WAFProbeResult(
            target=target,
            waf_detected=waf_detected,
            waf_name=waf_name,
            confidence=confidence,
            blocked_payloads=blocked,
            passed_payloads=passed,
            signature_hits=signature_hits,
            baseline_status=baseline_status,
            suggested_evasions=suggested,
            raw_responses=raw_responses,
        )

    def suggest_evasion(self, waf_name: str) -> List[str]:
        """Get evasion techniques for a specific WAF."""
        return EVASION_TECHNIQUES.get(waf_name, EVASION_TECHNIQUES.get("generic_block", []))
